### ISSUE TITLE
Will this wear leveling work on ESP8266 (Nodemcu) modules ?

### ISSUE THREAD

**Issue by amguamgu** [chayanforyou/WearLeveling#1]
I have tested this on arduino its working fine.
But when i used this for esp8266 its giving below error

fatal error: avr/io.h: No such file or directory

 #include <avr/io.h>

                    ^

compilation terminated.
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by chayanforyou** [comment]
Sorry, Currently no support for ESP8266.
